services:
  nyt-stats-discord-bot:
    build: .
    image: nyt-stats-discord-bot
    networks:
      - bot-network
    volumes:
      - ./database:/app/database

networks:
  bot-network:
    driver: bridge
