services:
  nyt-stats-discord-bot:
    build: .
    image: nyt-stats-discord-bot
    env_file:
      - .env
    # Alternatively you can set the environment variables as such:
    # /!\ The token shouldn't be written here, as this file is not ignored from Git /!\
    # environment:
    #   - PREFIX=YOUR_BOT_PREFIX_HERE
    #   - INVITE_LINK=YOUR_BOT_INVITE_LINK_HERE
    networks:
      - bot-network
    volumes:
      - ./database:/bot/database
      - ./discord.log:/bot/discord.log

networks:
  bot-network:
    driver: bridge
